# 🧩 Day 1 Practice — 15 Questions (up to Slicing)

**Topics covered:** array creation · `dtype` / `astype` · attributes · indexing · slicing · boolean indexing
**Level:** Medium · **Rule:** solve using only these topics — no loops!

**Q1.** Create an array of the first 12 **odd numbers** using a single **np.arange** call.

**Q2.** Using **np.linspace**, create 9 equally spaced values from 5 to 45. Before running, **predict the gap** between consecutive values - then verify.

**Q3.** Create **np.arange(1, 10)** and **np.linspace(1, 9, 9)**. Print both and compare their **dtype**. Why are they different?

**Q4.** Create a **6x6 identity matrix** with integer dtype - the output must show no decimal points.

**Q5.** Create a **3x4 matrix** where every element is **5**, and report its shape, size, and ndim.

**Q6.** Given **a = np.array([2, 4, 6])** and **b = np.array([2.0, 4.0, 6.0])** - check both dtypes, then convert b to int with **astype** and verify the dtypes now match.

**Q7.** **Predict the exact output** of **np.array([10.9, 25.5, 39.99]).astype(int)** before running it. What rule does the result prove?

**Q8.** Given **arr = np.arange(10, 101, 10)** - extract: (a) the 4th element, (b) the last element using negative indexing, (c) the 2nd-last element.

**Q9.** From the same arr, slice out exactly **[30 40 50 60]**, and separately produce the **full array in reverse**.

**Q10.** Given **arr = np.arange(1, 21)** - extract **every 3rd element starting from index 1** (result: 2, 5, 8, ...).

**Q11.** Using **one slice only**, extract everything from arr (1-20) EXCEPT the first two and the last two elements.

**Q12.** Using the matrix below, extract: (a) the **3rd row**, (b) the **last column**, (c) the **centre 3x3 block**.
```python
m = np.array([[ 1,  2,  3,  4,  5],
              [ 6,  7,  8,  9, 10],
              [11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25]])
```

**Q13.** From the same matrix, extract the **four corner elements** as a 2x2 array - using **step slicing only**.

**Q14.** From the same matrix, extract **every alternate row AND every alternate column** at the same time (the result is 3x3).

**Q15.** Given the marks array below - (a) extract all marks **greater than 60**; (b) extract marks **between 50 and 80** using two conditions with & (remember the parentheses!).
```python
marks = np.array([56, 91, 44, 77, 62, 85, 39, 70])
```

In [2]:
import numpy as np

In [4]:
# Q1
x = np.arange(1,25,2)
print(x)

[ 1  3  5  7  9 11 13 15 17 19 21 23]


In [5]:
# Q2
y = np.linspace(5,45,9)
print(y)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45.]


In [ ]:
# Q3
x = np.arange(1,10) # Gives a list of int
print(x)
y = np.linspace(1,9,9) # gives a list of Float values
print(y)

[1 2 3 4 5 6 7 8 9]
[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [13]:
# Q4
print(np.eye(6,dtype='int32'))


[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


In [ ]:
# Q5
a = np.full((3,4),5)
print(a)
print(a.shape) # shape
print(a.size) # no. of all elements
print(a.ndim) # no. of Dimensions

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
(3, 4)
12
2


In [25]:
# Q6
a = np.array([2,4,6])
print(a)
print(a.dtype)
b = np.array([2.0,4.0,6.0],dtype='int64')
print(b)
print(b.dtype)

[2 4 6]
int64
[2 4 6]
int64


In [ ]:
# Q7
print(np.array([10.9,25.33,99.08]).astype(int))  # astype creates a new array and do not change the original one.

[10 25 99]


In [35]:
# Q8
arr = np.arange(10,101,10)
print(arr)
print(arr[3]) # 3rd idx has the 4th index
print(arr[-1])
print(arr[-2])


[ 10  20  30  40  50  60  70  80  90 100]
40
100
90


In [36]:
# Q9
arr1 = arr[-4:-9:-1]
print(arr1)


[70 60 50 40 30]


In [38]:
# Q10
arr = np.arange(1,21)
print(arr)
arr1 = arr[1::3]
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 2  5  8 11 14 17 20]


In [39]:
# Q11
arr2 = arr[2:-2:1]
print(arr2)

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [48]:
# Q12
m = np.array([[ 1,  2,  3,  4,  5],
              [ 6,  7,  8,  9, 10],
              [11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25]])
print(m[2 , ::])
print()
print(m[:: , -1])
print()
print(m[1:-1:1 , 1:-1:1])

[11 12 13 14 15]

[ 5 10 15 20 25]

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [49]:
# Q13
s = m[::4 , ::4]
print(s)

[[ 1  5]
 [21 25]]


In [50]:
# Q14
s1 = m[::2 , ::2]
print(s1)


[[ 1  3  5]
 [11 13 15]
 [21 23 25]]


In [53]:
# Q15
marks = np.array([56, 91, 44, 77, 62, 85, 39, 70])
print(marks[marks > 60])
print(marks[(marks>50) & (marks<80)])

[91 77 62 85 70]
[56 77 62 70]


#### Completed the Assignment