In [2]:
import numpy as np

# Broadcasting 

## What is Broadcasting?

Broadcasting lets NumPy perform operations on arrays of **different sizes** without writing loops.

NumPy automatically **stretches** the smaller array to match the bigger one (without actually copying the data).

---

## Rule

Compare the shapes **from right to left**.

Broadcasting works if:

- ✅ Both numbers are the same.
- ✅ One of them is `1`.
- ❌ Otherwise, it gives an error.

---

## Example 1: Scalar + Array

```python
a = np.array([1, 2, 3])

a + 5
```

Output:

```python
[6 7 8]
```

Think of it as:

```python
[1,2,3]
+
[5,5,5]
```

---

## Example 2: Matrix + Row

```python
A = np.array([[1,2,3],
              [4,5,6]])

B = np.array([10,20,30])

A + B
```

Output:

```python
[[11 22 33]
 [14 25 36]]
```

The row is used for **every row** of the matrix.

---

## Example 3: Matrix + Column

```python
A = np.array([[1,2,3],
              [4,5,6]])

B = np.array([[10],
              [20]])

A + B
```

Output:

```python
[[11 12 13]
 [24 25 26]]
```

The column is used for **every column**.

---

# Tricky Examples

### ✅ Works

Shapes:

```text
(2,3)
(3,)
```

Compare from right:

```text
3 = 3 ✅
2 has no pair → treated as 1 ✅
```

Result shape:

```text
(2,3)
```

---

### ✅ Works

Shapes:

```text
(4,1)
(4,5)
```

Comparison:

```text
1 vs 5 → ✅
4 vs 4 → ✅
```

Result:

```text
(4,5)
```

---

### ❌ Doesn't Work

Shapes:

```text
(2,3)
(2,)
```

Comparison:

```text
3 vs 2 ❌
```

Error!

---

### ❌ Doesn't Work

Shapes:

```text
(2,3)
(3,2)
```

Comparison:

```text
3 vs 2 ❌
```

Error!

---

## Easy Trick to Remember

> Start comparing from the **last number** in the shape.

Only ask two questions:

- Are they equal?
- Is one of them `1`?

If **yes** → Broadcasting works.

If **no** → Error.

---

## Where is it Used?

- Adding a number to every element
- Normalizing data
- Adding bias in Machine Learning
- Fast array calculations

---

## One-Line Summary

> **Same or One → Works. Different → Error.**