In [2]:
import numpy as np

In [ ]:
print(np.array([1,2.5,"hello"])) # it should throw error but it converts every elment to the string type
x = np.array([1,4,4.5,9.8], dtype='int') # we can also define the data type but decimal value is removed not rounded off.
print(x)

['1' '2.5' 'hello']
[1 4 4 9]


In [ ]:
y = np.array([1,4,4.5,9.8])
print(y.astype('int')) # .astype creates a new copy and do not change the original array.

[1 4 4 9]


In [22]:
# arithmetic - array with scalar, array with array
arr = np.arange(10)
print(arr)
arr = arr+5
arr += 5 # added 5 to each element
print("ADD =",arr)
arr = arr*2
print("Multiply =",arr)
arr = arr**2 # exponent
print("Power of two =",arr)

arr1 = np.arange(11,21)
print(arr1)

print("arr + arr1 =",arr + arr1) # length should be same
print("arr * arr1 =",arr*arr1)


[0 1 2 3 4 5 6 7 8 9]
ADD = [10 11 12 13 14 15 16 17 18 19]
Multiply = [20 22 24 26 28 30 32 34 36 38]
Power of two = [ 400  484  576  676  784  900 1024 1156 1296 1444]
[11 12 13 14 15 16 17 18 19 20]
arr + arr1 = [ 411  496  589  690  799  916 1041 1174 1315 1464]
arr * arr1 = [ 4400  5808  7488  9464 11760 14400 17408 20808 24624 28880]


In [25]:
x = np.arange(6).reshape(2,3)
y = np.arange(3)
print("x = ", x)
print()
print("y = ", y)
print()
print(x+y)


x =  [[0 1 2]
 [3 4 5]]

y =  [0 1 2]

[[0 2 4]
 [3 5 7]]


In [30]:
# comparison operators - boolean arrays
x = np.arange(5)
y = np.arange(1,6)

print(x)
print(y)

print(x!=y) # checks all the elements
print(x>y)
print(x<y)

[0 1 2 3 4]
[1 2 3 4 5]
[ True  True  True  True  True]
[False False False False False]
[ True  True  True  True  True]


### The np.random Module

In [ ]:
# np.random.seed() + np.random.rand()
np.random.seed(3) # seed makes the internal formula static, value will be random but way of generation will be same
print(np.random.rand(4))  # range is from 0 to 1{ excluded }
print(np.random.randn(10)) # it creates random numbers in a normal distribution format

[0.5507979  0.70814782 0.29090474 0.51082761]
[-0.2773882  -0.35475898 -0.08274148 -0.62700068 -0.04381817 -0.47721803
 -1.31386475  0.88462238  0.88131804  1.70957306]


In [58]:
# np.random.randit(low , high , size) low included , high excluded
print(np.random.randint(3,10,10))

[6 7 5 3 3 7 7 7 7 6]


In [ ]:
# np.random.choice() 
lst = [3,454,6,7,34,90,0]
np.random.choice(lst,6,replace=False) # replace = false - chooses form lst but do not repeat the element from lst

array([ 90,   6,   3,   0, 454,   7])

In [ ]:
#  np.random.shuffle()
z = np.arange(10)
np.random.shuffle(z) # suffles the whole array
print(z)

[1 7 2 8 6 4 9 3 5 0]


##### Practice Set - Random & Statistics

In [ ]:
# Q1

np.random.seed(42)
x = np.random.randint(1,7,10)
print(x)

[4 5 3 5 5 2 3 3 3 5]


In [ ]:
# Q2

lst = ['Aman' , 'Priya' , 'Rahul' , 'Sneha' , 'Vikram']
print(np.random.choice(lst , 3 , replace=False))

['Aman' 'Priya' 'Rahul']


### Statistics

In [78]:
#min ,max ,sum, mean, median, std
arr = np.arange(6).reshape(2,3)
print(arr)
print("min : ",arr.min())
print("row min : ",arr.min(axis=1))
print("col min : ",arr.min(axis=0))

print("sum of arr : ",arr.sum())
print("sum of row : ",arr.sum(axis=1))

print("mean of arr : ",np.mean(arr))

[[0 1 2]
 [3 4 5]]
min :  0
row min :  [0 3]
col min :  [0 1 2]
sum of arr :  15
sum of row :  [ 3 12]
mean of arr :  2.5
