In [50]:
import numpy as np

# Broadcasting 

## What is Broadcasting?

Broadcasting lets NumPy perform operations on arrays of **different sizes** without writing loops.

NumPy automatically **stretches** the smaller array to match the bigger one (without actually copying the data).

---

## Rule

Compare the shapes **from right to left**.
from right to left as padding is added to the left if dimesions mismatch.

Broadcasting works if:

- ✅ Both numbers are the same.
- ✅ One of them is `1`.
- ❌ Otherwise, it gives an error.

---

## Example 1: Scalar + Array

```python
a = np.array([1, 2, 3])

a + 5
```

Output:

```python
[6 7 8]
```

Think of it as:

```python
[1,2,3]
+
[5,5,5]
```

---

## Example 2: Matrix + Row

```python
A = np.array([[1,2,3],
              [4,5,6]])

B = np.array([10,20,30])

A + B
```

Output:

```python
[[11 22 33]
 [14 25 36]]
```

The row is used for **every row** of the matrix.

---

## Example 3: Matrix + Column

```python
A = np.array([[1,2,3],
              [4,5,6]])

B = np.array([[10],
              [20]])

A + B
```

Output:

```python
[[11 12 13]
 [24 25 26]]
```

The column is used for **every column**.

---

# Tricky Examples

### ✅ Works

Shapes:

```text
(2,3)
(3,)
```

Compare from right:

```text
3 = 3 ✅
2 has no pair → treated as 1 ✅
```

Result shape:

```text
(2,3)
```

---

### ✅ Works

Shapes:

```text
(4,1)
(4,5)
```

Comparison:

```text
1 vs 5 → ✅
4 vs 4 → ✅
```

Result:

```text
(4,5)
```

---

### ❌ Doesn't Work

Shapes:

```text
(2,3)
(2,)
```

Comparison:

```text
3 vs 2 ❌
```

Error!

---

### ❌ Doesn't Work

Shapes:

```text
(2,3)
(3,2)
```

Comparison:

```text
3 vs 2 ❌
```

Error!

---

## Easy Trick to Remember

> Start comparing from the **last number** in the shape.

Only ask two questions:

- Are they equal?
- Is one of them `1`?

If **yes** → Broadcasting works.

If **no** → Error.

---

## Where is it Used?

- Adding a number to every element
- Normalizing data
- Adding bias in Machine Learning
- Fast array calculations

---

## One-Line Summary

> **Same or One → Works. Different → Error.**

#### Row vector:
[3,4,5,6]
shape = (1,4)

#### Column vector:
[[3],
[4],
[5],
[6]]
shape = (4,1)

In [51]:
x = np.array([3,4,5,6])
y = np.array([[3],
[4],
[5],
[6]])

print(x+y)

[[ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]]


### Reshaping

In [52]:
# reshape( rows , col)- size must match
arr = np.arange(12).reshape(4,-1) # -1 check the required row or col accourding to the total elements provided.
print(arr)
print(arr.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
(4, 3)


In [53]:
# use -1 for row and col vector
arr = np.arange(10)
arr1 = arr.reshape(1 , -1) # converts to the row vector
print("row vector :", arr1) 
arr2 = arr.reshape(-1 , 1) # converts to the col vector
print("col vector :" ,arr2)

row vector : [[0 1 2 3 4 5 6 7 8 9]]
col vector : [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [54]:
# np.newaxis - turn 1D into a row/col vector
arr1 = np.arange(12) # this is 1D array
print(arr1)
print("1D :" ,arr1.shape)
print()
arr1 = arr1[:,np.newaxis] # this converts one D array to 2D. we can change the ' : ' to change the shape
print(arr1)
print("2D :",arr1.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
1D : (12,)

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]
2D : (12, 1)


In [55]:
# flatten() vs ravel() -- changes any dimension to the 1D

arr = np.arange(12).reshape(4,3)
print("original array :" ,arr)
print()
arr1 = arr.ravel() #ravel creates a shallow copy
arr1[0] = 99 # change is reflected in the original array
arr2 = arr.flatten() #flatten creates a deep copy
arr2[1] = 100
print()
print("original array :" ,arr)
print()
print("ravel :",arr1)
print("flatten :",arr2)


original array : [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


original array : [[99  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

ravel : [99  1  2  3  4  5  6  7  8  9 10 11]
flatten : [ 99 100   2   3   4   5   6   7   8   9  10  11]


### Questions

In [56]:
# Q1
m = np.ones((3,4),dtype='int')
y = np.array([10,20,30]).reshape(3,1)
print(m+y)

[[11 11 11 11]
 [21 21 21 21]
 [31 31 31 31]]


In [57]:
# Q2
x = np.arange(1,11).reshape(10,1)
y = np.arange(1,11)
print(x*y)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [58]:
# np.vstack() and np.hstack() - vertical and horizontal stacking

arr1 = np.array([[1, 3, 4], [2, 3, 5]])
arr2 = np.array([[5, 6, 7], [8, 9, 10], [10, 11, 14]])
print(arr1)
print(arr2)
arr3 = np.vstack((arr1, arr2)) # no.of col should be same
print(arr3)
arr4 = np.hstack((arr1,arr2)) # no. of rows should be same
print(arr4)

[[1 3 4]
 [2 3 5]]
[[ 5  6  7]
 [ 8  9 10]
 [10 11 14]]
[[ 1  3  4]
 [ 2  3  5]
 [ 5  6  7]
 [ 8  9 10]
 [10 11 14]]


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 3

In [60]:
# np.concatenate() with axis
# axis -> 0 vstack
# axis -> 1 hstack 
print(arr1)
print(arr2)
print()
print(np.concatenate((arr2, arr1), axis = 0))

[[1 3 4]
 [2 3 5]]
[[ 5  6  7]
 [ 8  9 10]
 [10 11 14]]

[[ 5  6  7]
 [ 8  9 10]
 [10 11 14]
 [ 1  3  4]
 [ 2  3  5]]


In [ ]:
# np.where(condition, true_val , false_val)

arr = np.array([2,-10,20,-15,-18,10])
arr1 = np.where(arr<0 , 0 , arr) # 0 at -ve elements
print(arr1)

[ 2  0 20  0  0 10]


In [62]:
arr2 = np.array([20,40,55,75,80,35])
result = np.where(arr2>40 , "PASS" , "FAIL")
print(result)

['FAIL' 'FAIL' 'PASS' 'PASS' 'PASS' 'FAIL']
