In [6]:
! pip3 install numpy


[notice] A new release of pip is available: 25.3 -> 26.2
[notice] To update, run: pip3 install --upgrade pip


In [1]:
import numpy as np

# NumPy array:

In [ ]:
x = np.array([1,2,3,4,5])
print(x)
print(type(x))



[1 2 3 4 5]
<class 'numpy.ndarray'>


In [14]:
# np.zeros(), np.ones(), np.full()
print(np.zeros(5)) # by Default Float values 
print(np.zeros(5,dtype='int32')) # int values
print(np.zeros((3,4),dtype='int')) # 2D array formation

print(np.ones((2,4,5)))

[0. 0. 0. 0. 0.]
[0 0 0 0 0]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [ ]:
# np.arange(start , stop , step) , stop is excluded.
print(np.arange(10,5,-2))
print(np.arange(10))
print(np.arange(1,11).reshape(2,5)) # reshape should be used in a way that number of elements are equal in arange and reshape

[10  8  6]
[0 1 2 3 4 5 6 7 8 9]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [23]:
# np.linspace(start , stop , num)  it divides the range from start to end in num equal parts
print(np.linspace(1,10,3))
print(np.linspace(1,10,2))
print(np.linspace(1,10,5))

[ 1.   5.5 10. ]
[ 1. 10.]
[ 1.    3.25  5.5   7.75 10.  ]


In [ ]:
# np.eye(n) , gives a identity matrix of n*n 
# print(np.eye(4))
# print(np.eye(3,4))
print(np.eye(3,4,k=2)) # k=2 shifts the principle diagonal 

[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


### Array Attributes


In [34]:
# .shape .ndim .size .dtype
x = np.arange(20).reshape(4,5)
print(x)
print(x.shape)

# ndim tells number of dimensions
# size tells number of elements

print(len(x)) # tells the length of the 1st dimesion only

# dtype tells the datatype
print(type(x))
print(x.dtype)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
(4, 5)
4
<class 'numpy.ndarray'>
int64


### Indexing and Slicing

In [38]:
arr = np.arange(10)
print(arr)
print(arr[-3]) # negative indexing
print(arr[-3:-12:-2])

[0 1 2 3 4 5 6 7 8 9]
7
[7 5 3 1]


In [ ]:
# 2D indexing - arr[row ,col] , full row , full column
arr = np.arange(20).reshape(5,4)
print(arr)
print(arr[2][2]) # cell index


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
10


In [48]:
# Subarray Slicing
# print(arr)
# print(arr[2: , 1:])
# print(arr[::4 , ::3]) # print all the corner elements.
print(arr[1:3:1 , -2::-1])


[[ 6  5  4]
 [10  9  8]]
